apiVersion: apps/v1
kind: Deployment
metadata:
  name: openelb-manager
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube
      containers:
        # Change the value of image field below to your controller image URL
        - image: kubespheredev/openelb:v0.4.2
          name: openelb-manager
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
